[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
api_url = "http://localhost"

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://leadsbysaul.netlify.app"
additional_redirect_urls = [
  "https://leadsbysaul.netlify.app/auth/callback",
  "http://localhost:8888/auth/callback",
  "http://localhost:3000/auth/callback",
]
jwt_expiry = 3600
enable_signup = false

[auth.rate_limit]
email_sent = 20
sign_in_sign_ups = 30
token_verifications = 30

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "60s"
otp_length = 6
otp_expiry = 900

[auth.email.smtp]
enabled = true
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "login@mail.exotiq.ai"
sender_name = "Exotiq Command Center"

[auth.email.template.magic_link]
subject = "Your secure Exotiq Command Center sign-in"
content_path = "./supabase/templates/magic-link.html"

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
